# Use uma imagem oficial do Node.js
FROM node:21.7.2

# Diretório de trabalho
WORKDIR /root/bem-web

# Copia os arquivos de dependência
COPY package.json package-lock.json ./

# Instala dependências
RUN npm install

# Copia o restante do projeto
COPY . .

# Expõe a porta usada pelo React dev server
EXPOSE 3000

# Inicia o app em modo desenvolvimento com hot reload
CMD ["npm", "start"]
